//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelClient.HotelReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelData", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class HotelData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StarRatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StarRating {
            get {
                return this.StarRatingField;
            }
            set {
                if ((this.StarRatingField.Equals(value) != true)) {
                    this.StarRatingField = value;
                    this.RaisePropertyChanged("StarRating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelReference.IHotelOperations")]
    public interface IHotelOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotels", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelsResponse")]
        HotelClient.HotelReference.HotelData[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotels", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelReference.HotelData[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelById", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIdResponse")]
        HotelClient.HotelReference.HotelData GetHotelById(int hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelById", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelReference.HotelData> GetHotelByIdAsync(int hotelId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelOperationsChannel : HotelClient.HotelReference.IHotelOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelOperationsClient : System.ServiceModel.ClientBase<HotelClient.HotelReference.IHotelOperations>, HotelClient.HotelReference.IHotelOperations {
        
        public HotelOperationsClient() {
        }
        
        public HotelOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelClient.HotelReference.HotelData[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelReference.HotelData[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public HotelClient.HotelReference.HotelData GetHotelById(int hotelId) {
            return base.Channel.GetHotelById(hotelId);
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelReference.HotelData> GetHotelByIdAsync(int hotelId) {
            return base.Channel.GetHotelByIdAsync(hotelId);
        }
    }
}
